package com.unfbx.chatgpt.entity.chat;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.unfbx.chatgpt.entity.chat.tool.ToolCalls;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;

import java.io.Serializable;
import java.util.List;

/**
 * 描述：
 *
 * @author grt1228
 * @since 1.1.2
 * 2023-03-02
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@AllArgsConstructor
public class BaseMessage implements Serializable {

    /**
     * 目前支持四个中角色参考官网，进行情景输入：
     * <a href="https://platform.openai.com/docs/guides/chat/introduction">Role</a>
     */
    private String role;


    private String name;

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @since 1.1.2
     */
    @JsonProperty("tool_calls")
    private List<ToolCalls> toolCalls;

    /**
     * @since 1.1.2
     */
    @JsonProperty("tool_call_id")
    private String toolCallId;

    /**
     * 是否为前缀消息
     *
     * @since 1.1.3
     */
    private Boolean prefix;

    /**
     * 推理内容
     *
     * @since 1.1.3
     */
    @JsonProperty("reasoning_content")
    private String reasoningContent;

    /**
     * 推理信息
     *
     * @since 1.1.3
     */
    private String reasoning;
    
    /**
     * 已废弃，请使用 toolCalls
     * @deprecated 使用 toolCalls 替代
     */
    @Deprecated
    @JsonProperty("function_call")
    private FunctionCall functionCall;



    /**
     * 构造函数
     *
     * @param role         角色
     * @param name         name
     * @param toolCalls    工具调用列表
     * @param toolCallId   工具调用ID
     */
    public BaseMessage(String role, String name, List<ToolCalls> toolCalls, String toolCallId) {
        this.role = role;
        this.name = name;
        this.toolCalls = toolCalls;
        this.toolCallId = toolCallId;
    }

    public BaseMessage() {
    }


    @Getter
    @AllArgsConstructor
    public enum Role {

        SYSTEM("system"),
        USER("user"),
        ASSISTANT("assistant"),
        FUNCTION("function"),
        TOOL("tool"),
        DEVELOPER("developer"),
        ;
        private final String name;
    }

}
